### ISSUE TITLE
documentation

### ISSUE THREAD

**Issue by omayma96** [omayma96/projet-C2N3#3]
- [x] SASS

- [x] NodeJs

- [x] BEM

**Comment by omayma96** [comment]
j'ai compris BEM

**Comment by omayma96** [comment]
j'ai maîtrisé les notions de bases nécessaires du SASS

**Comment by omayma96** [comment]
j'ai compris le nodeJS , et comment compiler un fichier scss sans le plugin de VScode mais en utilisant cette fois le npm (node-sass) et le terminal pour qu'on puisse compiler facilement.

**Comment by omayma96** [comment]
après la documentation, j'ai amélioré beaucoup de chose et maintenant je peux commencer la partie code en utilisant la technologie SASS et la compilation via node-sass, ainsi en appliquant le concept du BEM

**Comment by youssefbm** [comment]
Good job keep up omayma
